name = input("Enter your name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
gender = input("Enter your gender: ")
price = input("Enter it's price: ")

print()
print("----- Student Information -----")
print("Name:", name)
print("Age:", age)
print("City:", city)
print("Gender:", gender)
print("Price:", price)